#!/usr/bin/env bash
# A script that install Nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html
sudo service nginx restart
