#!/usr/bin/env bash
#script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

for file in $(ls -p | grep -v / | grep -v '^\.' | sort)
do
	name=$(echo "$file" | cut -d '-' -f 2-)
	echo "$name"
done
