#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sed -i 's/31.13.66.35/8.8.8.8/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
